// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Upope.Loyalty;

namespace Upope.Loyalty.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190217213221_LoyaltyInit")]
    partial class LoyaltyInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Upope.Loyalty.Data.Entities.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Points");

                    b.Property<int>("Status");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Point");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Points = 10,
                            Status = 1,
                            UserId = "0fc04ca0-cc8d-4896-a50d-b9fe247cf152"
                        },
                        new
                        {
                            Id = 2,
                            Points = 20,
                            Status = 1,
                            UserId = "3282d1a0-ed0e-4f8a-8720-8f3474c21ecf"
                        },
                        new
                        {
                            Id = 3,
                            Points = 30,
                            Status = 1,
                            UserId = "ad687285-5202-4f81-8220-0a424dae3566"
                        },
                        new
                        {
                            Id = 4,
                            Points = 40,
                            Status = 1,
                            UserId = "897b2d91-6c1a-4bed-a4fc-9e84441e4b2d"
                        },
                        new
                        {
                            Id = 5,
                            Points = 50,
                            Status = 1,
                            UserId = "5961efe4-8ad8-488f-8727-022417b612a0"
                        },
                        new
                        {
                            Id = 6,
                            Points = 60,
                            Status = 1,
                            UserId = "d589a0cf-7172-4b44-bb49-609fcc7d56be"
                        },
                        new
                        {
                            Id = 7,
                            Points = 70,
                            Status = 1,
                            UserId = "e21b42d9-ca1f-49d5-b2f8-565a1bff3754"
                        },
                        new
                        {
                            Id = 8,
                            Points = 80,
                            Status = 1,
                            UserId = "b41b9a6b-00da-46dc-8115-67066009b211"
                        },
                        new
                        {
                            Id = 9,
                            Points = 90,
                            Status = 1,
                            UserId = "3eec55e4-3f38-4191-b43f-ba950108b296"
                        },
                        new
                        {
                            Id = 10,
                            Points = 100,
                            Status = 1,
                            UserId = "04dc0f14-65ce-4d93-8505-124d9f3b9276"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
